// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PMList(arg1) {
  return window['go']['main']['App']['PMList'](arg1);
}
