// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function PMList(arg1:main.FileInput):Promise<string>;

export function ProcessFiles(arg1:Array<string>):Promise<void>;
