// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function PMDrop(arg1:main.CSVData):Promise<string>;

export function PMList(arg1:main.FileInput):Promise<string>;
